sudo: required
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
- make dependencies
before_script:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
script:
- make travis
after_success:
- make coveralls
deploy:
  provider: pypi
  user: "Ben.Timby"
  password:
    secure: "CwfEq0SYcw1CpNrdjMFD/R8rCZVWwTeDZQZj6Z4LIi2PUd++BdDcB9S/NVCjChxD4C9CrausH/iFoPnBYFyNf5c13BTxuo5oFC7PUY99a/PjHR8vjGC48lj5KGE4W5O2qQQkgKojcP6rD8e1YPmaO9miRKIT9DLRpIqnSW4p+jI="
  on:
    tags: true
